In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Load Data
raw_df = pd.read_csv("./crsp-2.csv")

In [3]:
# Check Data
raw_df

      Unnamed: 0        date  permno       ret         prc     shrout
0        2873115  2000-01-31   10104 -0.108477   49.953125  2847344.0
1        2883897  2000-02-29   10104  0.486393   74.250000  2838409.0
2        2891757  2000-03-31   10104  0.051347   78.062500  2838409.0
3        2897954  2000-04-28   10104  0.024019   79.937500  2838409.0
4        2911756  2000-05-31   10104 -0.100860   71.875000  2807572.0
...          ...         ...     ...       ...         ...        ...
8275     4874507  2022-08-31   92655 -0.042427  519.330017   935383.0
8276     4891888  2022-09-30   92655 -0.024339  505.040009   935383.0
8277     4897944  2022-10-31   92655  0.099220  555.150024   935383.0
8278     4908957  2022-11-30   92655 -0.013312  547.760010   934349.0
8279     4915936  2022-12-30   92655 -0.029082  530.179993   934349.0

[8280 rows x 6 columns]

In [4]:
# Convet "date" column in to datetime data type
raw_df["date"] = pd.to_datetime(raw_df["date"])

In [5]:
raw_df

      Unnamed: 0       date  permno       ret         prc     shrout
0        2873115 2000-01-31   10104 -0.108477   49.953125  2847344.0
1        2883897 2000-02-29   10104  0.486393   74.250000  2838409.0
2        2891757 2000-03-31   10104  0.051347   78.062500  2838409.0
3        2897954 2000-04-28   10104  0.024019   79.937500  2838409.0
4        2911756 2000-05-31   10104 -0.100860   71.875000  2807572.0
...          ...        ...     ...       ...         ...        ...
8275     4874507 2022-08-31   92655 -0.042427  519.330017   935383.0
8276     4891888 2022-09-30   92655 -0.024339  505.040009   935383.0
8277     4897944 2022-10-31   92655  0.099220  555.150024   935383.0
8278     4908957 2022-11-30   92655 -0.013312  547.760010   934349.0
8279     4915936 2022-12-30   92655 -0.029082  530.179993   934349.0

[8280 rows x 6 columns]

In [6]:
df_ret = pd.pivot(raw_df, values="ret", index="date", columns="permno")
df_prc = pd.pivot(raw_df, values="prc", index="date", columns="permno")
df_shrout = pd.pivot(raw_df, values="shrout", index="date", columns="permno")
df_mktcap = df_prc * df_shrout

In [7]:
df_ret

permno,10104,10107,11308,11850,13856,14541,14593,17778,18163,20482,...,62092,65875,66181,76076,83443,84398,84788,86580,87055,92655
date,,,,,,,,,,,,,,,,,,,,,
2000-01-31,-0.108477,-0.161670,-0.013948,0.035687,-0.031915,-0.034632,0.009119,-0.087344,-0.074661,-0.098589,...,0.154167,0.012345,-0.176364,0.022170,-0.100546,-0.049362,-0.151888,-0.210386,0.072603,-0.002353
2000-02-29,0.486393,-0.086845,-0.153428,-0.092105,-0.058608,-0.099103,0.104819,-0.140625,-0.130489,0.013436,...,-0.097473,-0.209889,0.020971,0.207192,-0.125152,-0.015667,0.066796,0.726813,0.014049,-0.035377
2000-03-31,0.051347,0.188811,-0.031208,0.034855,0.089805,0.237657,0.184842,0.300000,-0.357041,0.066288,...,0.304000,0.249042,0.116368,0.169740,0.263889,0.096832,-0.027223,0.320068,0.059194,0.166846
2000-04-28,0.024019,-0.343529,0.006658,-0.003208,0.051971,-0.079108,-0.086516,0.036713,0.063186,0.097762,...,-0.049080,-0.024376,-0.124031,-0.103274,0.052816,-0.035121,-0.176306,0.054929,0.028537,0.118449
2000-05-31,-0.100860,-0.103047,0.129630,0.078069,0.114140,0.093539,-0.322922,-0.011804,0.112971,0.058537,...,-0.041935,-0.107595,-0.136062,-0.178724,-0.015722,-0.015723,-0.124575,0.280505,-0.409249,0.118088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-31,-0.047405,-0.066432,-0.038336,-0.004746,-0.015375,-0.026255,-0.031137,-0.067284,-0.006983,-0.056872,...,-0.088718,-0.094826,-0.035289,-0.014327,-0.065868,-0.040802,-0.060615,-0.168970,-0.035470,-0.042427
2022-09-30,-0.176399,-0.109267,-0.085075,-0.086620,-0.045626,-0.091041,-0.120977,-0.035219,-0.084747,-0.057379,...,-0.069372,-0.091844,-0.043270,-0.105546,-0.049074,-0.092119,-0.108622,-0.195508,-0.095441,-0.024339
2022-10-31,0.283609,-0.003306,0.068368,0.269156,0.112214,0.259135,0.109551,0.094915,0.073927,0.027387,...,0.013368,0.001383,0.073168,0.145250,0.105123,0.081276,-0.093451,0.111871,0.063798,0.099220
2022-11-30,0.063533,0.102055,0.070175,0.012995,0.021643,0.021172,-0.033129,0.079160,0.107596,0.087326,...,0.089986,0.043083,0.100496,0.094431,0.079671,0.055592,-0.057595,0.254131,0.075274,-0.013312
2022-12-30,-0.015537,-0.060045,0.000000,-0.009341,-0.019945,-0.020839,-0.122273,-0.024088,0.016090,0.020543,...,-0.016476,0.010775,-0.025093,-0.041834,-0.030446,-0.057566,-0.129894,-0.136442,-0.153454,-0.029082

In [8]:
df_prc

permno,10104,10107,11308,11850,13856,14541,14593,17778,18163,20482,...,62092,65875,66181,76076,83443,84398,84788,86580,87055,92655
date,,,,,,,,,,,,,,,,,,,,,
2000-01-31,49.953125,97.875000,57.437500,83.437500,34.125000,83.625000,103.750000,51200.00000,101.062500,32.562500,...,17.312500,61.937500,56.625000,109.500000,1646.000000,139.625000,64.562500,37.062500,48.937500,53.000000
2000-02-29,74.250000,89.375000,48.625000,75.312500,32.125000,74.687500,114.625000,44000.00000,87.875000,33.000000,...,15.625000,48.937500,57.812500,132.187500,1440.000000,137.437500,68.875000,64.000000,49.625000,51.125000
2000-03-31,78.062500,106.250000,46.937500,77.937500,34.875000,92.437500,135.812500,57200.00000,56.500000,35.187500,...,20.375000,61.125000,64.500000,77.312500,1820.000000,150.375000,67.000000,84.484375,52.562500,59.625000
2000-04-28,79.937500,69.750000,47.250000,77.687500,36.687500,85.125000,124.062500,59300.00000,59.750000,38.437500,...,19.375000,59.250000,56.500000,69.328125,1916.125000,145.093750,55.187500,89.125000,54.062500,66.687500
2000-05-31,71.875000,62.562500,53.375000,83.312500,40.875000,92.437500,84.000000,58600.00000,66.500000,40.687500,...,18.562500,52.875000,48.812500,56.937500,1886.000000,142.812500,48.312500,114.125000,31.937500,74.562500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-31,74.150002,261.470001,61.709999,95.589996,172.270004,158.059998,157.220001,421308.00000,137.940002,102.650002,...,545.320007,41.810001,288.420013,44.720001,280.799988,395.179993,126.769997,150.940002,522.099976,519.330017
2022-09-30,61.070000,232.899994,56.020000,87.309998,163.259995,143.669998,138.199997,406470.00000,126.250000,96.760002,...,507.190002,37.970001,275.940002,40.000000,267.019989,357.179993,113.000000,121.389999,472.269989,505.040009
2022-10-31,78.070000,232.130005,59.849998,110.809998,181.580002,180.899994,153.339996,445050.00000,134.669998,98.940002,...,513.969971,37.369999,296.130005,45.430000,295.089996,386.209991,102.440002,134.970001,501.500000,555.150024
2022-11-30,83.029999,255.139999,63.610001,111.339996,185.509995,183.309998,148.029999,480280.00000,149.160004,107.580002,...,560.219971,38.980000,323.989990,49.720001,318.600006,407.679993,96.540001,169.229996,539.250000,547.760010
2022-12-30,81.739998,239.820007,63.610001,110.300003,180.660004,179.490005,129.929993,468710.96875,151.559998,109.790001,...,550.690002,39.400002,315.859985,47.639999,308.899994,382.429993,84.000000,146.139999,456.500000,530.179993

In [9]:
df_shrout

permno,10104,10107,11308,11850,13856,14541,14593,17778,18163,20482,...,62092,65875,66181,76076,83443,84398,84788,86580,87055,92655
date,,,,,,,,,,,,,,,,,,,,,
2000-01-31,2847344.0,5160025.0,2469980.0,3461574.0,1455698.0,656266.0,161159.0,1342.0,1315714.0,1537311.0,...,158237.0,1552786.0,2302364.0,3271171.0,5342.0,27109.0,340787.0,30717.0,444774.0,169753.0
2000-02-29,2838409.0,5160025.0,2469980.0,3461574.0,1455698.0,656266.0,161159.0,1342.0,1315714.0,1537311.0,...,158237.0,1552786.0,2302364.0,3271171.0,5342.0,102670.0,340787.0,30717.0,444774.0,169753.0
2000-03-31,2838409.0,5242000.0,2472451.0,3479892.0,1443516.0,656266.0,162680.0,1341.0,1315714.0,1547694.0,...,156801.0,1552786.0,2302364.0,6542342.0,5387.0,102670.0,349959.0,30717.0,444774.0,169753.0
2000-04-28,2838409.0,5262405.0,2472451.0,3479892.0,1443516.0,654871.0,162680.0,1341.0,1315714.0,1547694.0,...,156904.0,1550659.0,2308810.0,7001000.0,5387.0,102670.0,351774.0,32222.0,444774.0,163289.0
2000-05-31,2807572.0,5262405.0,2475093.0,3481127.0,1441018.0,651970.0,162744.0,1341.0,1307893.0,1549423.0,...,155877.0,1545656.0,2308810.0,7023852.0,5387.0,102670.0,351774.0,32222.0,449937.0,162409.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-31,2664926.0,7457892.0,4324629.0,4167636.0,1379906.0,1957435.0,16070752.0,614.0,2389554.0,1751220.0,...,391789.0,4199715.0,1023726.0,4110000.0,1301126.0,908332.0,10187555.0,2490000.0,442664.0,935383.0
2022-09-30,2695653.0,7457000.0,4324629.0,4167636.0,1379000.0,1957435.0,15943425.0,614.0,2389554.0,1751220.0,...,391789.0,4199715.0,1023726.0,4108844.0,1301126.0,916782.0,10198000.0,2490000.0,442604.0,935383.0
2022-10-31,2695653.0,7454473.0,4324513.0,4167636.0,1377709.0,1957435.0,15908118.0,614.0,2369697.0,1751220.0,...,391789.0,4199817.0,1023726.0,4103000.0,1301126.0,950932.0,10201654.0,2460000.0,442604.0,935383.0
2022-11-30,2696166.0,7454473.0,4324513.0,4118293.0,1377709.0,1933639.0,15908118.0,597.0,2369697.0,1743574.0,...,392196.0,4199817.0,1019186.0,4108103.0,1301981.0,948932.0,10201654.0,2460000.0,443841.0,934349.0
2022-12-30,2696253.0,7454473.0,4324513.0,4118293.0,1377709.0,1933639.0,15908118.0,597.0,2369697.0,1743574.0,...,392196.0,4199817.0,1019186.0,4108103.0,1301981.0,938182.0,10201654.0,2460000.0,443841.0,934349.0

In [10]:
### Portfolio Formation & Backtesting ###

In [11]:
# Cretae an empty dataframe to store value
df_weight= pd.DataFrame(np.zeros_like(df_ret), index=df_ret.index, columns=df_ret.columns)
pf_ret = pd.DataFrame(np.zeros(len(df_ret)), index=df_ret.index, columns=["pf_value"])

In [12]:
df_weight

permno,10104,10107,11308,11850,13856,14541,14593,17778,18163,20482,...,62092,65875,66181,76076,83443,84398,84788,86580,87055,92655
date,,,,,,,,,,,,,,,,,,,,,
2000-01-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2000-02-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2000-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2000-04-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2000-05-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022-09-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022-10-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022-11-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022-12-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
pd.Timedelta(days=1) + pd.Timedelta(days=1)

Timedelta('2 days 00:00:00')

In [14]:
date_index = df_ret.index.copy().tolist()
for cnt, idx in enumerate(df_ret.index):
    print(cnt, idx)

0 2000-01-31 00:00:00
1 2000-02-29 00:00:00
2 2000-03-31 00:00:00
3 2000-04-28 00:00:00
4 2000-05-31 00:00:00
5 2000-06-30 00:00:00
6 2000-07-31 00:00:00
7 2000-08-31 00:00:00
8 2000-09-29 00:00:00
9 2000-10-31 00:00:00
10 2000-11-30 00:00:00
11 2000-12-29 00:00:00
12 2001-01-31 00:00:00
13 2001-02-28 00:00:00
14 2001-03-30 00:00:00
15 2001-04-30 00:00:00
16 2001-05-31 00:00:00
17 2001-06-29 00:00:00
18 2001-07-31 00:00:00
19 2001-08-31 00:00:00
20 2001-09-28 00:00:00
21 2001-10-31 00:00:00
22 2001-11-30 00:00:00
23 2001-12-31 00:00:00
24 2002-01-31 00:00:00
25 2002-02-28 00:00:00
26 2002-03-28 00:00:00
27 2002-04-30 00:00:00
28 2002-05-31 00:00:00
29 2002-06-28 00:00:00
30 2002-07-31 00:00:00
31 2002-08-30 00:00:00
32 2002-09-30 00:00:00
33 2002-10-31 00:00:00
34 2002-11-29 00:00:00
35 2002-12-31 00:00:00
36 2003-01-31 00:00:00
37 2003-02-28 00:00:00
38 2003-03-31 00:00:00
39 2003-04-30 00:00:00
40 2003-05-30 00:00:00
41 2003-06-30 00:00:00
42 2003-07-31 00:00:00
43 2003-08-29 00:00:00
44 2003-09-30 00:00:00
45 2003-10-31 00:00:00
46 2003-11-28 00:00:00
47 2003-12-31 00:00:00
48 2004-01-30 00:00:00
49 2004-02-27 00:00:00
50 2004-03-31 00:00:00
51 2004-04-30 00:00:00
52 2004-05-28 00:00:00
53 2004-06-30 00:00:00
54 2004-07-30 00:00:00
55 2004-08-31 00:00:00
56 2004-09-30 00:00:00
57 2004-10-29 00:00:00
58 2004-11-30 00:00:00
59 2004-12-31 00:00:00
60 2005-01-31 00:00:00
61 2005-02-28 00:00:00
62 2005-03-31 00:00:00
63 2005-04-29 00:00:00
64 2005-05-31 00:00:00
65 2005-06-30 00:00:00
66 2005-07-29 00:00:00
67 2005-08-31 00:00:00
68 2005-09-30 00:00:00
69 2005-10-31 00:00:00
70 2005-11-30 00:00:00
71 2005-12-30 00:00:00
72 2006-01-31 00:00:00
73 2006-02-28 00:00:00
74 2006-03-31 00:00:00
75 2006-04-28 00:00:00
76 2006-05-31 00:00:00
77 2006-06-30 00:00:00
78 2006-07-31 00:00:00
79 2006-08-31 00:00:00
80 2006-09-29 00:00:00
81 2006-10-31 00:00:00
82 2006-11-30 00:00:00
83 2006-12-29 00:00:00
84 2007-01-31 00:00:00
85 2007-02-28 00:00:00
86 2007-03-30 00:00:00
87 2007-04-30 00:00:00
88 2007-05-31 00:00:00
89 2007-06-29 00:00:00
90 2007-07-31 00:00:00
91 2007-08-31 00:00:00
92 2007-09-28 00:00:00
93 2007-10-31 00:00:00
94 2007-11-30 00:00:00
95 2007-12-31 00:00:00
96 2008-01-31 00:00:00
97 2008-02-29 00:00:00
98 2008-03-31 00:00:00
99 2008-04-30 00:00:00
100 2008-05-30 00:00:00
101 2008-06-30 00:00:00
102 2008-07-31 00:00:00
103 2008-08-29 00:00:00
104 2008-09-30 00:00:00
105 2008-10-31 00:00:00
106 2008-11-28 00:00:00
107 2008-12-31 00:00:00
108 2009-01-30 00:00:00
109 2009-02-27 00:00:00
110 2009-03-31 00:00:00
111 2009-04-30 00:00:00
112 2009-05-29 00:00:00
113 2009-06-30 00:00:00
114 2009-07-31 00:00:00
115 2009-08-31 00:00:00
116 2009-09-30 00:00:00
117 2009-10-30 00:00:00
118 2009-11-30 00:00:00
119 2009-12-31 00:00:00
120 2010-01-29 00:00:00
121 2010-02-26 00:00:00
122 2010-03-31 00:00:00
123 2010-04-30 00:00:00
124 2010-05-28 00:00:00
125 2010-06-30 00:00:00
126 2010-07-30 00:00:00
127 2010-08-31 00:00:00
128 2010-09-30 00:00:00
129 2010-10-29 00:00:00
130 2010-11-30 00:00:00
131 2010-12-31 00:00:00
132 2011-01-31 00:00:00
133 2011-02-28 00:00:00
134 2011-03-31 00:00:00
135 2011-04-29 00:00:00
136 2011-05-31 00:00:00
137 2011-06-30 00:00:00
138 2011-07-29 00:00:00
139 2011-08-31 00:00:00
140 2011-09-30 00:00:00
141 2011-10-31 00:00:00
142 2011-11-30 00:00:00
143 2011-12-30 00:00:00
144 2012-01-31 00:00:00
145 2012-02-29 00:00:00
146 2012-03-30 00:00:00
147 2012-04-30 00:00:00
148 2012-05-31 00:00:00
149 2012-06-29 00:00:00
150 2012-07-31 00:00:00
151 2012-08-31 00:00:00
152 2012-09-28 00:00:00
153 2012-10-31 00:00:00
154 2012-11-30 00:00:00
155 2012-12-31 00:00:00
156 2013-01-31 00:00:00
157 2013-02-28 00:00:00
158 2013-03-28 00:00:00
159 2013-04-30 00:00:00
160 2013-05-31 00:00:00
161 2013-06-28 00:00:00
162 2013-07-31 00:00:00
163 2013-08-30 00:00:00
164 2013-09-30 00:00:00
165 2013-10-31 00:00:00
166 2013-11-29 00:00:00
167 2013-12-31 00:00:00
168 2014-01-31 00:00:00
169 2014-02-28 00:00:00
170 2014-03-31 00:00:00
171 2014-04-30 00:00:00
172 2014-05-30 00:00:00
173 2014-06-30 00:00:00
174 2014-07-31 00:00:00
175 2014-08-29 00:00:00
176 2014-09-30 00:00:00
177 2014-10-31 00:00:00
178 2014-11-28 00:00:00
179 2014-12-31 00:00:00
180 2015-01-30 00:00:00
181 2015-02-27 00:00:00
182 2015-03-31 00:00:00
183 2015-04-30 00:00:00
184 2015-05-29 00:00:00
185 2015-06-30 00:00:00
186 2015-07-31 00:00:00
187 2015-08-31 00:00:00
188 2015-09-30 00:00:00
189 2015-10-30 00:00:00
190 2015-11-30 00:00:00
191 2015-12-31 00:00:00
192 2016-01-29 00:00:00
193 2016-02-29 00:00:00
194 2016-03-31 00:00:00
195 2016-04-29 00:00:00
196 2016-05-31 00:00:00
197 2016-06-30 00:00:00
198 2016-07-29 00:00:00
199 2016-08-31 00:00:00
200 2016-09-30 00:00:00
201 2016-10-31 00:00:00
202 2016-11-30 00:00:00
203 2016-12-30 00:00:00
204 2017-01-31 00:00:00
205 2017-02-28 00:00:00
206 2017-03-31 00:00:00
207 2017-04-28 00:00:00
208 2017-05-31 00:00:00
209 2017-06-30 00:00:00
210 2017-07-31 00:00:00
211 2017-08-31 00:00:00
212 2017-09-29 00:00:00
213 2017-10-31 00:00:00
214 2017-11-30 00:00:00
215 2017-12-29 00:00:00
216 2018-01-31 00:00:00
217 2018-02-28 00:00:00
218 2018-03-29 00:00:00
219 2018-04-30 00:00:00
220 2018-05-31 00:00:00
221 2018-06-29 00:00:00
222 2018-07-31 00:00:00
223 2018-08-31 00:00:00
224 2018-09-28 00:00:00
225 2018-10-31 00:00:00
226 2018-11-30 00:00:00
227 2018-12-31 00:00:00
228 2019-01-31 00:00:00
229 2019-02-28 00:00:00
230 2019-03-29 00:00:00
231 2019-04-30 00:00:00
232 2019-05-31 00:00:00
233 2019-06-28 00:00:00
234 2019-07-31 00:00:00
235 2019-08-30 00:00:00
236 2019-09-30 00:00:00
237 2019-10-31 00:00:00
238 2019-11-29 00:00:00
239 2019-12-31 00:00:00
240 2020-01-31 00:00:00
241 2020-02-28 00:00:00
242 2020-03-31 00:00:00
243 2020-04-30 00:00:00
244 2020-05-29 00:00:00
245 2020-06-30 00:00:00
246 2020-07-31 00:00:00
247 2020-08-31 00:00:00
248 2020-09-30 00:00:00
249 2020-10-30 00:00:00
250 2020-11-30 00:00:00
251 2020-12-31 00:00:00
252 2021-01-29 00:00:00
253 2021-02-26 00:00:00
254 2021-03-31 00:00:00
255 2021-04-30 00:00:00
256 2021-05-28 00:00:00
257 2021-06-30 00:00:00
258 2021-07-30 00:00:00
259 2021-08-31 00:00:00
260 2021-09-30 00:00:00
261 2021-10-29 00:00:00
262 2021-11-30 00:00:00
263 2021-12-31 00:00:00
264 2022-01-31 00:00:00
265 2022-02-28 00:00:00
266 2022-03-31 00:00:00
267 2022-04-29 00:00:00
268 2022-05-31 00:00:00
269 2022-06-30 00:00:00
270 2022-07-29 00:00:00
271 2022-08-31 00:00:00
272 2022-09-30 00:00:00
273 2022-10-31 00:00:00
274 2022-11-30 00:00:00
275 2022-12-30 00:00:00

In [21]:
# Step 2. Complement code that implements backtesting for value weight portfolio

date_index = df_ret.index.copy().tolist()
for cnt, idx in enumerate(df_ret.index):
    if cnt == 0:
        continue

    else:
        target_weight = df_mktcap.loc[date_index[cnt-1]] / df_mktcap.loc[date_index[cnt-1]].sum()
        current_weight = (1+df_ret.loc[date_index[cnt-1]]) * df_weight.loc[date_index[cnt-1]]
        current_weight = current_weight / current_weight.sum()
        weight_difference = np.abs(target_weight - current_weight)

        df_weight.loc[date_index[cnt]] = target_weight
        pf_ret.loc[date_index[cnt],"pf_value"]  = (df_ret.loc[date_index[cnt]] * df_weight.loc[date_index[cnt]]).sum() - (weight_difference.sum() * 0.002)

In [22]:
df_weight

permno,10104,10107,11308,11850,13856,14541,14593,17778,18163,20482,...,62092,65875,66181,76076,83443,84398,84788,86580,87055,92655
date,,,,,,,,,,,,,,,,,,,,,
2000-01-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2000-02-29,0.046191,0.164014,0.046073,0.093798,0.016132,0.017823,0.005430,0.022314,0.043183,0.016257,...,0.000890,0.031234,0.042339,0.116325,0.002856,0.001229,0.007145,0.000370,0.007069,0.002922
2000-03-31,0.071079,0.155537,0.040506,0.087924,0.015772,0.016531,0.006230,0.019915,0.038994,0.017110,...,0.000834,0.025628,0.044891,0.145835,0.002594,0.004759,0.007916,0.000663,0.007444,0.002927
2000-04-28,0.067792,0.170407,0.035507,0.082980,0.015403,0.018561,0.006760,0.023469,0.022744,0.016662,...,0.000977,0.029040,0.045436,0.154755,0.003000,0.004724,0.007174,0.000794,0.007153,0.003097
2000-05-31,0.073242,0.118484,0.037710,0.087267,0.017095,0.017995,0.006515,0.025669,0.025376,0.019203,...,0.000981,0.029658,0.042108,0.156676,0.003332,0.004809,0.006267,0.000927,0.007762,0.003515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-31,0.014762,0.148993,0.019796,0.029061,0.017180,0.022900,0.185849,0.019736,0.023717,0.013561,...,0.016670,0.013804,0.022010,0.013270,0.027504,0.026690,0.097833,0.032170,0.017063,0.036208
2022-09-30,0.014826,0.146310,0.020023,0.029891,0.017836,0.023214,0.189574,0.019409,0.024731,0.013488,...,0.016030,0.013175,0.022154,0.013790,0.027413,0.026932,0.096899,0.028199,0.017341,0.036447
2022-10-31,0.013528,0.142718,0.019908,0.029902,0.018501,0.023110,0.181065,0.020509,0.024791,0.013925,...,0.016329,0.013104,0.023214,0.013506,0.028550,0.026909,0.094698,0.024839,0.017177,0.038821
2022-11-30,0.016081,0.132223,0.019777,0.035288,0.019115,0.027057,0.186394,0.020880,0.024385,0.013239,...,0.015387,0.011993,0.023165,0.014243,0.029338,0.028063,0.079854,0.025371,0.016961,0.039679
2022-12-30,0.016470,0.139927,0.020238,0.033735,0.018803,0.026078,0.173251,0.021095,0.026005,0.013800,...,0.016165,0.012044,0.024294,0.015027,0.030518,0.028462,0.072458,0.030628,0.017609,0.037654

In [17]:
# Step 3. Scalable Code
# def generate_weight_func():
#     ~ ~ ~
#     return weight


def generate_mktcap_weight(date_index, when, mktcap_df):
    """
    date_index (lits): date index
    when (int): 0 for now, - for past, + for future
    mktcap_df (DataFrame): market capitalization dataframe
    """

    weight = mktcap_df.loc[date_index[when]] / mktcap_df.loc[date_index[when]].sum()

    return weight

date_index = df_ret.index.copy().tolist()
for cnt,idx in enumerate(df_ret.index):
    if cnt == 0:
        continue

    else:
        target_weight = generate_mktcap_weight(date_index, cnt-1, df_mktcap)
        current_weight = (1+df_ret.loc[date_index[cnt-1]]) * df_weight.loc[date_index[cnt-1]]
        current_weight = current_weight / current_weight.sum()
        weight_difference = np.abs(target_weight - current_weight)

        df_weight.loc[date_index[cnt]] = target_weight
        pf_ret.loc[date_index[cnt],"pf_value"]  = (df_ret.loc[date_index[cnt]] * df_weight.loc[date_index[cnt]]).sum() - (weight_difference.sum() * 0.002)

In [18]:
# Step 3. Scalable Code -- With minimum varaince
# def generate_weight_func():
#     ~ ~ ~
#     return weight

def generate_minvar_weight(date_index, when, df_ret):
    returns = df_ret.loc[:date_index[when]].mean(axis=0).values
    covariance = df_ret.cov().values

    I = np.ones_like(returns)
    weight = np.linalg.solve(covariance, I)
    weight = weight / np.sum(weight)

    return weight

date_index = df_ret.index.copy().tolist()
for cnt,idx in enumerate(df_ret.index):
    if cnt == 0:
        continue

    elif idx < pd.to_datetime("2020"):
        continue

    else:
        target_weight = generate_minvar_weight(date_index, cnt-1, df_ret)
        current_weight = (1+df_ret.loc[date_index[cnt-1]]) * df_weight.loc[date_index[cnt-1]]
        current_weight = current_weight / current_weight.sum()
        weight_difference = np.abs(target_weight - current_weight)

        df_weight.loc[date_index[cnt]] = target_weight
        pf_ret.loc[date_index[cnt],"pf_value"]  = (df_ret.loc[date_index[cnt]] * df_weight.loc[date_index[cnt]]).sum() - (weight_difference.sum() * 0.002)

In [19]:
df_weight

permno,10104,10107,11308,11850,13856,14541,14593,17778,18163,20482,...,62092,65875,66181,76076,83443,84398,84788,86580,87055,92655
date,,,,,,,,,,,,,,,,,,,,,
2000-01-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2000-02-29,0.046191,0.164014,0.046073,0.093798,0.016132,0.017823,0.005430,0.022314,0.043183,0.016257,...,0.000890,0.031234,0.042339,0.116325,0.002856,0.001229,0.007145,0.000370,0.007069,0.002922
2000-03-31,0.071079,0.155537,0.040506,0.087924,0.015772,0.016531,0.006230,0.019915,0.038994,0.017110,...,0.000834,0.025628,0.044891,0.145835,0.002594,0.004759,0.007916,0.000663,0.007444,0.002927
2000-04-28,0.067792,0.170407,0.035507,0.082980,0.015403,0.018561,0.006760,0.023469,0.022744,0.016662,...,0.000977,0.029040,0.045436,0.154755,0.003000,0.004724,0.007174,0.000794,0.007153,0.003097
2000-05-31,0.073242,0.118484,0.037710,0.087267,0.017095,0.017995,0.006515,0.025669,0.025376,0.019203,...,0.000981,0.029658,0.042108,0.156676,0.003332,0.004809,0.006267,0.000927,0.007762,0.003515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-31,0.040068,0.043918,0.062233,0.169473,0.057756,-0.071202,0.044204,0.612153,0.229211,0.069017,...,-0.035774,0.016290,-0.005209,-0.016831,-0.474097,-0.066468,-0.007175,-0.015763,0.062362,0.054319
2022-09-30,0.040068,0.043918,0.062233,0.169473,0.057756,-0.071202,0.044204,0.612153,0.229211,0.069017,...,-0.035774,0.016290,-0.005209,-0.016831,-0.474097,-0.066468,-0.007175,-0.015763,0.062362,0.054319
2022-10-31,0.040068,0.043918,0.062233,0.169473,0.057756,-0.071202,0.044204,0.612153,0.229211,0.069017,...,-0.035774,0.016290,-0.005209,-0.016831,-0.474097,-0.066468,-0.007175,-0.015763,0.062362,0.054319
2022-11-30,0.040068,0.043918,0.062233,0.169473,0.057756,-0.071202,0.044204,0.612153,0.229211,0.069017,...,-0.035774,0.016290,-0.005209,-0.016831,-0.474097,-0.066468,-0.007175,-0.015763,0.062362,0.054319
2022-12-30,0.040068,0.043918,0.062233,0.169473,0.057756,-0.071202,0.044204,0.612153,0.229211,0.069017,...,-0.035774,0.016290,-0.005209,-0.016831,-0.474097,-0.066468,-0.007175,-0.015763,0.062362,0.054319

In [24]:
df_ret

permno,10104,10107,11308,11850,13856,14541,14593,17778,18163,20482,...,62092,65875,66181,76076,83443,84398,84788,86580,87055,92655
date,,,,,,,,,,,,,,,,,,,,,
2000-01-31,-0.108477,-0.161670,-0.013948,0.035687,-0.031915,-0.034632,0.009119,-0.087344,-0.074661,-0.098589,...,0.154167,0.012345,-0.176364,0.022170,-0.100546,-0.049362,-0.151888,-0.210386,0.072603,-0.002353
2000-02-29,0.486393,-0.086845,-0.153428,-0.092105,-0.058608,-0.099103,0.104819,-0.140625,-0.130489,0.013436,...,-0.097473,-0.209889,0.020971,0.207192,-0.125152,-0.015667,0.066796,0.726813,0.014049,-0.035377
2000-03-31,0.051347,0.188811,-0.031208,0.034855,0.089805,0.237657,0.184842,0.300000,-0.357041,0.066288,...,0.304000,0.249042,0.116368,0.169740,0.263889,0.096832,-0.027223,0.320068,0.059194,0.166846
2000-04-28,0.024019,-0.343529,0.006658,-0.003208,0.051971,-0.079108,-0.086516,0.036713,0.063186,0.097762,...,-0.049080,-0.024376,-0.124031,-0.103274,0.052816,-0.035121,-0.176306,0.054929,0.028537,0.118449
2000-05-31,-0.100860,-0.103047,0.129630,0.078069,0.114140,0.093539,-0.322922,-0.011804,0.112971,0.058537,...,-0.041935,-0.107595,-0.136062,-0.178724,-0.015722,-0.015723,-0.124575,0.280505,-0.409249,0.118088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-31,-0.047405,-0.066432,-0.038336,-0.004746,-0.015375,-0.026255,-0.031137,-0.067284,-0.006983,-0.056872,...,-0.088718,-0.094826,-0.035289,-0.014327,-0.065868,-0.040802,-0.060615,-0.168970,-0.035470,-0.042427
2022-09-30,-0.176399,-0.109267,-0.085075,-0.086620,-0.045626,-0.091041,-0.120977,-0.035219,-0.084747,-0.057379,...,-0.069372,-0.091844,-0.043270,-0.105546,-0.049074,-0.092119,-0.108622,-0.195508,-0.095441,-0.024339
2022-10-31,0.283609,-0.003306,0.068368,0.269156,0.112214,0.259135,0.109551,0.094915,0.073927,0.027387,...,0.013368,0.001383,0.073168,0.145250,0.105123,0.081276,-0.093451,0.111871,0.063798,0.099220
2022-11-30,0.063533,0.102055,0.070175,0.012995,0.021643,0.021172,-0.033129,0.079160,0.107596,0.087326,...,0.089986,0.043083,0.100496,0.094431,0.079671,0.055592,-0.057595,0.254131,0.075274,-0.013312
2022-12-30,-0.015537,-0.060045,0.000000,-0.009341,-0.019945,-0.020839,-0.122273,-0.024088,0.016090,0.020543,...,-0.016476,0.010775,-0.025093,-0.041834,-0.030446,-0.057566,-0.129894,-0.136442,-0.153454,-0.029082

In [20]:
pf_ret.iloc[240:,:]

            pf_value
date
2020-01-31  0.009733
2020-02-28 -0.089328
2020-03-31 -0.040696
2020-04-30  0.078086
2020-05-29  0.011127
2020-06-30 -0.000145
2020-07-31  0.073527
2020-08-31  0.043556
2020-09-30 -0.013062
2020-10-30 -0.018407
2020-11-30  0.070757
2020-12-31  0.040337
2021-01-29  0.014768
2021-02-26 -0.006548
2021-03-31  0.038402
2021-04-30  0.030011
2021-05-28  0.018062
2021-06-30  0.019755
2021-07-30  0.043081
2021-08-31  0.027572
2021-09-30 -0.041381
2021-10-29  0.069157
2021-11-30 -0.011962
2021-12-31  0.085887
2022-01-31 -0.021225
2022-02-28 -0.012773
2022-03-31  0.062014
2022-04-29 -0.014659
2022-05-31 -0.018511
2022-06-30 -0.025841
2022-07-29  0.061475
2022-08-31 -0.022372
2022-09-30 -0.052640
2022-10-31  0.077896
2022-11-30  0.069492
2022-12-30 -0.011682